const IMG = {
  bex: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
  gsx: 'https://images.pexels.com/photos/277593/pexels-photo-277593.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
  iot: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
  cctv: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
  expo: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
  smart: 'https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
  roadshow: 'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
  nrf: 'https://images.pexels.com/photos/1486223/pexels-photo-1486223.jpeg?auto=compress&cs=tinysrgb&w=400&h=200&fit=crop',
};

module.exports = {
  categories: ['IoT', 'CCTV'],
  events: [
    {
      title: 'BEX ASIA',
      image: IMG.bex,
      dateDisplay: 'Sept 4 - 6, 2025',
      startDate: new Date('2025-09-04'),
      endDate: new Date('2025-09-06'),
      location: 'Sands Expo & Convention Centre, Singapore',
      booth: 'B-E02',
      category: 'IoT',
      registrationUrl: 'https://example.com/register',
      status: 'register',
      sortOrder: 1,
    },
    {
      title: 'Global Security Exchange (GSX)',
      image: IMG.gsx,
      dateDisplay: 'Sept 10 - 12, 2025',
      startDate: new Date('2025-09-10'),
      endDate: new Date('2025-09-12'),
      location: 'Orange County Convention Center, Orlando, USA',
      booth: '3125',
      category: 'CCTV',
      registrationUrl: 'https://example.com/register',
      status: 'register',
      sortOrder: 2,
    },
    {
      title: 'IOTSWC',
      image: IMG.iot,
      dateDisplay: 'May 13 - 15, 2025',
      startDate: new Date('2025-05-13'),
      endDate: new Date('2025-05-15'),
      location: 'Gran Via Venue, Barcelona, Spain',
      booth: 'B16',
      category: 'IoT',
      registrationUrl: 'https://example.com/register',
      status: 'register',
      sortOrder: 3,
    },
    {
      title: 'Smart Building Day',
      image: IMG.smart,
      dateDisplay: 'Apr 24, 2025',
      startDate: new Date('2025-04-24'),
      endDate: new Date('2025-04-24'),
      location: 'Kowloon Shangri-La, Hong Kong',
      booth: 'Main Hall',
      category: 'IoT',
      registrationUrl: 'https://example.com/register',
      status: 'register',
      sortOrder: 4,
    },
    {
      title: 'SECTECH Roadshow',
      image: IMG.cctv,
      dateDisplay: 'May 8 / May 15 / May 20 / May 27, 2025',
      startDate: new Date('2025-05-08'),
      endDate: new Date('2025-05-27'),
      location: 'Brisbane & Sydney, Australia',
      booth: 'TBC',
      category: 'CCTV',
      registrationUrl: '',
      status: 'coming_soon',
      sortOrder: 5,
    },
    {
      title: 'NRF APAC',
      image: IMG.nrf,
      dateDisplay: 'June 3 - 5, 2025',
      startDate: new Date('2025-06-03'),
      endDate: new Date('2025-06-05'),
      location: 'Marina Bay Sands, Singapore',
      booth: 'SP22',
      category: 'IoT',
      registrationUrl: 'https://example.com/register',
      status: 'register',
      sortOrder: 6,
    },
    {
      title: 'Realcomm',
      image: IMG.expo,
      dateDisplay: 'June 3 - 4, 2025',
      startDate: new Date('2025-06-03'),
      endDate: new Date('2025-06-04'),
      location: 'Savannah Convention Center, USA',
      booth: '1021',
      category: 'IoT',
      registrationUrl: 'https://example.com/register',
      status: 'register',
      sortOrder: 7,
    },
    {
      title: 'AIRAH IAQ Conference',
      image: IMG.roadshow,
      dateDisplay: 'May 26 - 27, 2024',
      startDate: new Date('2024-05-26'),
      endDate: new Date('2024-05-27'),
      location: 'Melbourne, Australia',
      booth: 'A12',
      category: 'IoT',
      registrationUrl: '',
      status: 'ended',
      sortOrder: 8,
    },
  ],
};
