module.exports = [
  {
    title: '4MP Smart Dome Camera',
    model: 'NX-DS2143',
    slug: 'nx-ds2143-dome',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=600',
    description: 'High-performance dome camera with AI analytics and night vision.',
    categorySlug: 'network-products',
    subCategorySlug: 'ip-cameras',
    subSubCategorySlug: 'dome-cameras',
    isNew: true,
    sortOrder: 1,
  },
  {
    title: '8MP Bullet Camera',
    model: 'NX-BU2847',
    slug: 'nx-bu2847-bullet',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=600',
    description: 'Weatherproof bullet camera for outdoor perimeter protection.',
    categorySlug: 'network-products',
    subCategorySlug: 'ip-cameras',
    subSubCategorySlug: 'bullet-cameras',
    sortOrder: 2,
  },
  {
    title: 'Enterprise NVR 32-Channel',
    model: 'NX-NVR32',
    slug: 'nx-nvr32',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600',
    description: '32-channel network video recorder with RAID storage support.',
    categorySlug: 'network-products',
    subCategorySlug: 'nvr-storage',
    subSubCategorySlug: 'enterprise-nvr',
    sortOrder: 3,
  },
  {
    title: 'Face Recognition Terminal',
    model: 'NX-FR100',
    slug: 'nx-fr100',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=600',
    description: 'Touchless access control with face recognition and mask detection.',
    categorySlug: 'access-control',
    subCategorySlug: 'biometric-devices',
    subSubCategorySlug: 'face-recognition',
    isNew: true,
    sortOrder: 4,
  },
  {
    title: 'Video Door Phone',
    model: 'NX-VDP200',
    slug: 'nx-vdp200',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=600',
    description: 'HD video intercom with mobile app integration.',
    categorySlug: 'intercom-systems',
    subCategorySlug: 'door-stations',
    subSubCategorySlug: 'video-door-phones',
    sortOrder: 5,
  },
  {
    title: 'Smart LED Panel 40W',
    model: 'NX-LED40',
    slug: 'nx-led40',
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&q=80&w=600',
    description: 'Dimmable smart LED panel with occupancy-based automation.',
    categorySlug: 'smart-lighting',
    subCategorySlug: 'led-fixtures',
    subSubCategorySlug: 'indoor-panels',
    sortOrder: 6,
  },
];
