module.exports = [
  {
    title: '4MP Smart Dome Camera',
    model: 'NX-DS2143',
    slug: 'nx-ds2143-dome',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=600',
    description: 'High-performance dome camera with AI analytics and night vision.',
    categorySlug: 'network-products',
    subCategorySlug: 'ip-cameras',
    subSubCategorySlug: 'dome-cameras',
    isNew: true,
    isHot: true,
    sortOrder: 1,
    filterTags: ['4MP', 'Dome', 'Pro Series'],
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    ],
    featureIcons: ['PIR', 'SD', 'IR', 'IP67', 'H.265', 'ONVIF', 'PoE'],
    keyFeatures: [
      'High quality imaging with 4 MP resolution',
      'Clear imaging against strong back light due to DWDR technology',
      '3D DNR technology delivers clean and sharp images',
      'Built-in microphone for real-time audio security',
      'Water and dust resistant (IP67)',
      'EXIR 2.0 with advanced infrared technology',
    ],
    variants: ['NX-DS2143', 'NX-DS2143/W', 'NX-DS2143/Z'],
    dataSheetUrl: '/contact',
    resources: {
      documents: [
        { title: 'Data Sheet', url: '/contact', type: 'PDF' },
        { title: 'Quick Start Guide', url: '/contact', type: 'PDF' },
        { title: 'User Manual', url: '/contact', type: 'PDF' },
        { title: 'FAQ', url: '/contact', type: 'PDF' },
      ],
      firmware: [
        { title: 'Firmware V5.7.3 build 240801', url: '/contact', date: '8/1/2025' },
        { title: 'Firmware V5.7.2 build 240601', url: '/contact', date: '6/1/2025' },
      ],
    },
    specifications: {
      Camera: [
        { label: 'Image Sensor', value: '1/2.8" progressive scan CMOS' },
        { label: 'Max. Resolution', value: '2560 × 1440' },
        { label: 'Min. Illumination', value: 'Color: 0.005 Lux @ (F1.6, AGC ON); B/W: 0.001 Lux with IR' },
        { label: 'Shutter Speed', value: '1/3 s to 1/100,000 s' },
        { label: 'Day & Night', value: 'IR cut filter' },
        { label: 'Angle Adjustment', value: 'Pan: 0° to 360°; Tilt: 0° to 75°; Rotate: 0° to 360°' },
      ],
      Lens: [
        { label: 'Lens Type', value: 'Fixed focal' },
        { label: 'Focal Length', value: '2.8 mm' },
        { label: 'Aperture', value: 'Max. F1.6' },
        { label: 'Field of View', value: 'Horizontal: 103°; Vertical: 55°' },
      ],
      DORI: [
        { label: 'DORI Distance (Detect)', value: '62.5 m' },
        { label: 'DORI Distance (Observe)', value: '25.0 m' },
        { label: 'DORI Distance (Recognize)', value: '12.5 m' },
        { label: 'DORI Distance (Identify)', value: '6.3 m' },
      ],
      Illuminator: [
        { label: 'Supplement Light Type', value: 'IR' },
        { label: 'IR Range', value: 'Up to 30 m' },
      ],
      Video: [
        { label: 'Video Compression', value: 'H.265+/H.265/H.264+/H.264' },
        { label: 'Frame Rate', value: '25 fps @ 2560 × 1440' },
      ],
      Audio: [
        { label: 'Audio Input', value: 'Built-in microphone' },
        { label: 'Audio Compression', value: 'G.711' },
      ],
      Network: [
        { label: 'Protocols', value: 'IPv4/IPv6, HTTP, HTTPS, RTSP, ONVIF' },
        { label: 'Simultaneous Live View', value: 'Up to 20 channels' },
      ],
    },
  },
  {
    title: '6MP AcuSense Dome Camera',
    model: 'NX-DS2866',
    slug: 'nx-ds2866-dome',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=600',
    description: 'Motorized varifocal dome with AcuSense human/vehicle classification.',
    categorySlug: 'network-products',
    subCategorySlug: 'ip-cameras',
    subSubCategorySlug: 'dome-cameras',
    isNew: true,
    sortOrder: 2,
    filterTags: ['4MP', 'Dome', 'EasyIP 3.0'],
    keyFeatures: [
      '6 MP high resolution imaging',
      'AcuSense technology for accurate alarm detection',
      'Motorized varifocal lens for flexible installation',
      'IP67 weatherproof and IK10 vandal resistant',
    ],
    variants: ['NX-DS2866', 'NX-DS2866/Z'],
  },
  {
    title: '8MP Bullet Camera',
    model: 'NX-BU2847',
    slug: 'nx-bu2847-bullet',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=600',
    description: 'Weatherproof bullet camera for outdoor perimeter protection.',
    categorySlug: 'network-products',
    subCategorySlug: 'ip-cameras',
    subSubCategorySlug: 'bullet-cameras',
    isHot: true,
    sortOrder: 3,
    filterTags: ['8MP', 'Bullet', 'Pro Series'],
    keyFeatures: [
      '8 MP ultra HD resolution',
      'DarkFighter technology for low-light scenes',
      'IP67 rated for outdoor installation',
      'H.265+ compression saves bandwidth and storage',
    ],
  },
  {
    title: '4MP Smart Bullet Camera',
    model: 'NX-BU2143',
    slug: 'nx-bu2143-bullet',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=600',
    description: 'Compact bullet camera for corridor and perimeter monitoring.',
    categorySlug: 'network-products',
    subCategorySlug: 'ip-cameras',
    subSubCategorySlug: 'bullet-cameras',
    isNew: true,
    sortOrder: 4,
    filterTags: ['4MP', 'Bullet', 'EasyIP 3.0'],
  },
  {
    title: 'Enterprise NVR 32-Channel',
    model: 'NX-NVR32',
    slug: 'nx-nvr32',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600',
    description: '32-channel network video recorder with RAID storage support.',
    categorySlug: 'network-products',
    subCategorySlug: 'nvr-storage',
    subSubCategorySlug: 'enterprise-nvr',
    sortOrder: 3,
  },
  {
    title: 'Face Recognition Terminal',
    model: 'NX-FR100',
    slug: 'nx-fr100',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=600',
    description: 'Touchless access control with face recognition and mask detection.',
    categorySlug: 'access-control',
    subCategorySlug: 'biometric-devices',
    subSubCategorySlug: 'face-recognition',
    isNew: true,
    sortOrder: 4,
  },
  {
    title: 'Video Door Phone',
    model: 'NX-VDP200',
    slug: 'nx-vdp200',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=600',
    description: 'HD video intercom with mobile app integration.',
    categorySlug: 'intercom-systems',
    subCategorySlug: 'door-stations',
    subSubCategorySlug: 'video-door-phones',
    sortOrder: 5,
  },
  {
    title: 'Smart LED Panel 40W',
    model: 'NX-LED40',
    slug: 'nx-led40',
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&q=80&w=600',
    description: 'Dimmable smart LED panel with occupancy-based automation.',
    categorySlug: 'smart-lighting',
    subCategorySlug: 'led-fixtures',
    subSubCategorySlug: 'indoor-panels',
    sortOrder: 6,
  },
];
